version: '3'
services:

  mongo:
    container_name: mongo
    image: mongo
    environment:
      - MONGO_INITDB_DATABASE=pit
    volumes:
      - ./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - '27018:27017'

  maildev:
    container_name: maildev
    image: djfarrelly/maildev
    ports:
      - '1080:80'
      - '1025:25'

  author:
    container_name: author
    image: local/aem-dispatcher-author
    volumes:
      - ./aem-dispatcher/author/logs:/etc/httpd/logs
      - ./aem-dispatcher/author/dispatcher_cache:/etc/httpd/dispatcher_cache
    environment:
      - AEM_HOST=${MY_HOST}
      - AEM_PORT=${AUTHOR_PORT}
    ports:
      - '1083:80'
      - '1443:443'

  publisher:
    container_name: publisher
    image: local/aem-dispatcher-publisher
    volumes:
      - ./aem-dispatcher/publisher/logs:/etc/httpd/logs
      - ./aem-dispatcher/publisher/dispatcher_cache:/etc/httpd/dispatcher_cache
    environment:
      - AEM_HOST=${MY_HOST}
      - AEM_PORT=${PUBLISHER_PORT}
    ports:
      - '1084:80'
      - '2443:443'
